package ar.edu.utn.ap4.java.GUIA_EJERCICIO_10.InscripcionTest;

import static org.junit.Assert.*;
//import static org.junit.jupiter.api.Assertions.assertTrue;
//
//IMPORT ORG.JUNIT.AFTER;
//IMPORT ORG.JUNIT.AFTERCLASS;
//IMPORT ORG.JUNIT.BEFORE;
//IMPORT ORG.JUNIT.BEFORECLASS;
//IMPORT ORG.JUNIT.TEST;
//
//IMPORT AR.EDU.UTN.AP4.JAVA.GUIA_EJERCICIO_10.MATERIAS.MATERIA;
//IMPORT JUNIT.FRAMEWORK.ASSERT;
//
//PUBLIC CLASS INSCRIPCIONTEST {
//
//	@BEFORECLASS
//	PUBLIC STATIC VOID SETUPBEFORECLASS() THROWS EXCEPTION {
//	}
//
//	@AFTERCLASS
//	PUBLIC STATIC VOID TEARDOWNAFTERCLASS() THROWS EXCEPTION {
//	}
//
//	@BEFORE
//	PUBLIC VOID SETUP() THROWS EXCEPTION {
//	}
//
//	@AFTER
//	PUBLIC VOID TEARDOWN() THROWS EXCEPTION {
//	}
//
//	
//	@TEST
//
//	PUBLIC VOID APROBADOS) {
//		
//	)
//	) 
//	
//}	
